### ISSUE TITLE
Support variable depth top-level folders

### ISSUE THREAD

**Issue by panghy** [wavefrontHQ/wftop#15]
Support the concept of the top-level folder spanning multiple "folder" dividers. For example, foo.bar.baz and foo.baz.world would just have a single top-level folder "foo" but if we support multiple top-level folders and set that to 2, we would have two top-level folders "foo.bar" and "foo.baz".

**Comment by panghy** [comment]
@djia-vm-wf any updates on this?

**Comment by sushantdewan123** [comment]
Merged to master. Will close.
