### ISSUE TITLE
wftop not showing metrics under host

### ISSUE THREAD

**Issue by muhammadnkhan** [wavefrontHQ/wftop#16]
wftop not showing metrics under host.
Select: 
Spy On: Points
Analysis Dimension: Host
Group By : None

It doesn't show any metric s under host and later errors out with "EXPANSION HALTED PER CONFIG" error. See attachment
![image (1)](https://user-images.githubusercontent.com/34246923/68895817-ba411800-06ef-11ea-982b-0089015de486.png)

**Comment by panghy** [comment]
It’s halted based on the configuration limit (depth and number of nodes limit). Can try increasing those.
