### ISSUE TITLE
group by option changes to "Wavefront Ingestion Source" erroneously 

### ISSUE THREAD

**Issue by muhammadnkhan** [wavefrontHQ/wftop#17]
If you enter the config dialog and group by is set to "None". Some times it gets changed to "Wavefront Ingestion Source" even if you do unrelated changes  Like you open wftop, group by is None, you enter config to change something unrelated. You don't notice that the checkbox had moved to group by ingestion source and you submit the change.
I have also noticed that it sometimes defaults to "Wavefront Ingestion Source".
Make sure that the Group By is always defaulted to "None" and doesn't change to "Wavefront Ingestion Source" when other changes are made to the configuration dialog box.

**Comment by panghy** [comment]
@sushantdewan123 or @jbau can you guys assign this to someone?
